src/components/survey/Interest.tsx
src/components/survey/MbtiFifth.tsx
src/components/survey/MbtiFirst.tsx
src/components/survey/MbtiForth.tsx
src/components/survey/MbtiSecond.tsx
src/components/survey/MbtiThird.tsx
src/pages/Survey/index.tsx

> #31
> 아래의 구조로 반환되도록 변경했습니다.
```json
{
"answers": [
{"id": 1, "mbtiEffect": "E", "score": 7},
{"id": 2, "mbtiEffect": "N", "score": 7},
{"id": 3, "mbtiEffect": "T", "score": 7},
{"id": 4, "mbtiEffect": "J", "score": 7},
{"id": 5, "mbtiEffect": "E", "score": 6},
{"id": 6, "mbtiEffect": "S", "score": 6},
{"id": 7, "mbtiEffect": "T", "score": 6},
{"id": 8, "mbtiEffect": "P", "score": 5},
{"id": 9, "mbtiEffect": "E", "score": 7},
{"id": 10, "mbtiEffect": "N", "score": 7},
{"id": 11, "mbtiEffect": "F", "score": 7},
{"id": 12, "mbtiEffect": "P", "score": 7},
{"id": 13, "mbtiEffect": "E", "score": 1},
{"id": 14, "mbtiEffect": "N", "score": 1},
{"id": 15, "mbtiEffect": "T", "score": 1},
{"id": 16, "mbtiEffect": "J", "score": 1},
{"id": 17, "mbtiEffect": "E", "score": 4},
{"id": 18, "mbtiEffect": …
```

Refactor: 자녀 성향 진단 결과 반환값 구조 변경

---

src/pages/MyPage/index.tsx
src/pages/MyPageCreateChildProfile/index.tsx
src/pages/MyPageDetailChildProfile/index.tsx
src/pages/MyPageEditUserProfile/index.tsx

- 서버에서 유저 데이터를 가져오는 fetchUserData 함수 추가
> #33
> 마이페이지 api 구현

Feat: 유저 정보 조회 api 매핑

---

src/pages/Main/index.tsx

> #38
> 자녀 프로필 목록 조회 api 연동
> 자녀 프로필 검증 api 연동
> 도서 추천 목록 조회 api 연동
> 자녀 프로필 선택 
> 선택한 자녀 프로필 ID sessionStorage 저장
userId 토큰으로 변경해야 함

Feat: switch childprofile

---

src/pages/MyPage/index.tsx
src/pages/MyPageEditUserProfile/index.tsx
src/pages/MyPageManageChildProfile/index.tsx

> #33
> 자녀 프로필 삭제 api 매핑
> 유저 탈퇴 api 매핑

Feat: 마이페이지 api 매핑 (자녀 프로필 삭제, 유저 탈퇴)

---

package-lock.json
package.json
src/pages/BookList/index.tsx

> ex) #39
> 페이지 당 12개의 도서 카드 보이도록 했습니다.
> 검색 기능도 매핑 했습니다.   
> 도서 전체 페이지 
> 도서 검색 결과
부족한 부분 있다면 알려주세요!

Feat: 도서 전체 목록 api 매핑

---

package-lock.json
package.json
src/pages/BookDetail/index.tsx
src/pages/BookList/index.tsx

Feat: 도서 상세 페이지 api 매핑

---

src/pages/Main/index.tsx

> #49
> 추천책 반환 구조 변경 및 도서 이미지 포맷팅

Feat: 추천책 반환 구조 변경 및 도서 이미지 포맷팅

---

src/pages/Main/index.tsx

> #52 
> 메인페이지 인기책 목록 추가
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

Feat: 메인페이지 인기책 목록 추가

---

src/components/survey/Interest.tsx
src/components/surveyresult/ProgressLine.tsx
src/pages/ChildPersonalityHistoryDetail/index.tsx
src/pages/Survey/index.tsx
src/pages/SurveyResult/index.tsx
src/routes/RouteDef.tsx

Feat: API 매핑 (메인페이지, MBTI 설문)

---

src/pages/MyPage/index.tsx
src/pages/MyPageDetailChildProfile/index.tsx

Fix: 자녀 프로필 상세보기 페이지 수정

---

package-lock.json
package.json
src/modal/LoginModal.tsx
src/pages/Main/index.tsx

Feat: 로그인 모달 UI 구현

---

src/pages/Event/index.tsx
src/pages/Main/index.tsx

> #62
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

Feat: 현재 진행중인 이벤트 조회 및 참여 요청 API 매핑

---

src/pages/Admin/CreateBookList/index.tsx
src/pages/Admin/ManageBookList/index.tsx
src/pages/Admin/UpdateBookList/index.tsx

Feat: 관리자 페이지 토큰 적용

---

src/pages/Main/index.tsx

Feat: 메뉴 접근 제한 구현

---

src/pages/MyPage/index.tsx
src/pages/MyPageCreateChildProfile/index.tsx
src/pages/MyPageDetailChildProfile/index.tsx
src/pages/MyPageEditUserProfile/index.tsx
src/pages/MyPageManageChildProfile/index.tsx

> #67
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

Refactor: 자녀 프로필 관련 API 인증 사용자 반영

---

src/main.tsx
src/pages/Main/index.tsx

> ex) #52
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

Feat: 메인페이지 기본 추천 연동

---

src/pages/BookDetail/index.tsx
src/pages/BookList/index.tsx

Refactor: 도서 상세 좋아요/싫어요 토큰 적용

---

src/pages/BookDetail/index.tsx

Refactor: 좋아요 상태 반영

---

src/pages/BookDetail/index.tsx

> ex) #77
> 프론트 좋아요 상태 버그 수정했습니다.

Fix: 좋아요 상태 버그 수정

---

src/pages/Admin/CreateBookList/index.tsx
src/pages/Admin/UpdateBookList/index.tsx

> #40 
> mbti에 허깅페이스 적용한 후 도서 등록 및 삭제되도록 구현을 한 후,  API 매핑을 진행했습니다.

Feat: mbti에 허깅페이스 적용한 후 도서 등록 및 삭제되도록 구현후 API 매핑

---

src/modal/EventResultModal.tsx
src/pages/Main/index.tsx

Refactor: 이벤트 결과 UI 구현 및 API 매핑

---

src/modal/EventResultModal.tsx

> #79
> 이벤트 결과 모달 스크롤 가능하도록 수정

Refactor: 이벤트 결과 모달 스크롤 가능하도록 수정

---

src/modal/EventJoinCompleteModal.tsx
src/pages/EventInfo/index.tsx
src/pages/Login/index.tsx

> #79
> 이벤트 참여 완료 모달 구현
> 로그인 페이지 회원가입 링크 색상 변경

Feat: 이벤트 참여 완료 모달 구현

---

src/pages/Admin/ManageBookList/index.tsx

>  #14 
> 문제 상황 : 도서를 검색했을 때 현재 페이지에 있는 도서 리스트에서만 조회됨
> 해결 : 전체 도서 리스트로부터 검색해서 결과를 보여줌
> 문제 상황 : 페이지네이션에 도서 목록을 보여줄때 모든 페이지 수를 나타냄
> 해결 : 5개의 페이지만 보여줌
> 문제 상황 : 필터했을때 현재 페이지에 있는 도서 리스트에서만 조회됨
> 아직 해결못함

Refactor: 검색어 기능 및 페이지네이션 리팩토링

---

src/pages/Admin/ManageBookList/index.tsx

> #37 
> 현재 페이지에서만 도서가 필터링 되는 문제가 있어서 새로운 API 엔드포인트를 만들어서 구현했습니다.
> 단독으로 필터링 하는 경우에 일부 중복 데이터가 있는 문제가 있습니다..

Fix: 관리자 페이지 필터 기능 수정

---

src/pages/BookDetail/index.tsx

> ex) 
> 좋아요/싫어요 상태 알림 모달
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

refactor: 좋아요/싫어요 상태 알림 모달

---

src/pages/Admin/CreateBookList/index.tsx
src/pages/Admin/CreateEvent/index.tsx
src/pages/Admin/ManageBookList/index.tsx
src/pages/Admin/ManageEventList/index.tsx
src/pages/Admin/UpdateBookList/index.tsx
src/pages/Admin/UpdateEvent/index.tsx
src/routes/RouteDef.tsx

Feature: 관리자 이벤트 UI 구현 및 매핑
